#pragma once

// ohoh
// nope. not "ohoh", use object names instead - that is how it is done in D3; it is in D2 objects go by id index

// conflict
#undef ROBOT_GUIDEBOT
// hmmm, for non Windows, this will be 0 instead of 2 :/
#undef ROBOT_GUIDEBOTRED

// OBJ_ROBOT 2
enum
{
	ROBOT_GUIDEBOT = 0,
	ROBOT_CHAFF = 1,
	ROBOT_GUIDEBOTRED = 2,
	ROBOT_ENERGY = 3,
	ROBOT_INVULNERABILITY = 4,
	ROBOT_INVISIBILITY = 5,
	ROBOT_AFTERBURNER_COOLER = 6,
	ROBOT_CONVERTER= 7,
	ROBOT_FULLMAP = 8,
	ROBOT_GREEN_BALL = 9,
	ROBOT_QUADLASERS = 10,
	ROBOT_FLAG_BLUE = 11,
	ROBOT_FLAG_RED = 12,
	ROBOT_SHIELD = 13,
	ROBOT_CONCUSION = 14,
	ROBOT_FUSION = 15,
	ROBOT_GUIDED = 16,
	ROBOT_HOMING = 17,
	ROBOT_MEGA = 18,
	ROBOT_OMEGA = 19,
	ROBOT_PLASMA = 20,
	ROBOT_SMART = 21,
	ROBOT_SUPERLASER = 22,

	ROBOT_CYAN_BALL = 99,
	ROBOT_KEY_G1 = 100,
	ROBOT_KEY_xx = 101,
	ROBOT_KEY_yy = 102,
// ===== robots
	ROBOT_ORBOT = 103,
	ROBOT_TANK_FUSION = 104,
	ROBOT_GUIDEBOT_ = 105,
	ROBOT_TURRET_MACHINEGUN = 106,
//// 96, gyro
// 6b, gyro
	ROBOT_RAS1 = 107,
// tubbs (fist bot)
//	ROBOT_RAS2 = ,
	ROBOT_PILLAR = 108,
	ROBOT_ANTENA_THIN = 109,
// 6e
	ROBOT_TANK_VAUSS = 110,
// green plasmer
	ROBOT_SQUID = 111,
// tank camera
	ROBOT_CONS_MONITOR_DROID = 112,
	ROBOT_LOADER = 113,
	ROBOT_LIGHT_BLINKING_1 = 114,
	ROBOT_CAMERA_PTMC = 115,
	ROBOT_TURRET_LASER_RED = 116,
	ROBOT_FAN = 117,

// "Tank", tanker
	ROBOT_TANK = 125,

// "old scratch", grey
	ROBOT_OLD_SCRATCHER = 130,

// low damage tailbot
	ROBOT_red = 138,
// level 8 rotating thingy fastening
	ROBOT_fastening = 139,
// "thresher", fusion bot
	ROBOT_THRESHER = 140,
// white lasered
//	ROBOT_ = 141,
// welder
//	ROBOT_ = 142,
// jaws wall
//	ROBOT_ = 143,
// 90, "Tubbs"
	ROBOT_RAS2 = 144,
// 91, "Bird"
	ROBOT_BIRD = 145,
// 93, "Hopper", an animal
	ROBOT_DINOSAUR = 147,
// yellow laser test boss
//	ROBOT_ = 373,

// 9a, "Gunboy"
	ROBOT_GUNBOY = 154,
// 9b, "Stormtrooper"
	ROBOT_STORMTROOPER = 155,
// 9c, "Stormtroopergreen"
	ROBOT_STORMTROOPER_GREEN = 156,
// 9d, "Stormtrooperwhite"
	ROBOT_STORMTROOPER_WHITE = 157,
// 9e, "Seeker", player's
	ROBOT_SEEKER = 158,

// a2, "Thiefbot", green
	ROBOT_THIEF = 162,

// 11a, "superthief", green
	ROBOT_SUPERTHIEF = 284,

// 11c, "Bellbars"
	ROBOT_BELL_BARS = 286,

// 177, frag bot
	ROBOT_fragbot = 375,

// "Hellion"
	ROBOT_L15_BOSS = 379,

// "Blackpyro"
// *in "Vengeance" level it is ally
	ROBOT_MERCENARY_YELLOW_QUAD_LASER = 390,
// 1ae, red lasers bot
	ROBOT_SQUID_RED_LASER = 430,
//
	ROBOT_GYRO_NAPALM = 462,
//	ROBOT_ALIEN_TERRITORY_GREEN_PLASMA = 464,
	ROBOT_MERCENARY_GREEN_DUAL_LASER = 465,
	ROBOT_BOSS_HEAD = 466,
//	ROBOT_ALIEN_TERRITORY_GUARD = 466,
	ROBOT_MERCENARY_VAUSS = 486,
	ROBOT_MERCENARY_MD = 487,

//
	ROBOT_DESK_PTMC1 = 500,
	ROBOT_DESK_PTMC2 = 501,
	ROBOT_DESK_PTMC3 = 502,
	ROBOT_DESK_SIGNS1 = 503,

// "Khotel"
	ROBOT_KHOTEL = 517,

// 22d, plasma
	ROBOT_SQUID_PLASMA = 557,

// "L15 Thresher"
	ROBOT_L15_THRESHER = 517,

// 280, "Miniendboss", Mercenary level 6 helpers
	ROBOT_MERCENARY_OUR_GUNNER = 640,

// 288, "Finalboss(mercanary)"
// "alert !  intruder alert !" :)
	ROBOT_MERCENARY_BOSS = 648,

//	ROBOT_ = ,
};

// OBJ_POWERUP 7
enum
{
	POWERUP_CHAFF = 1,
	POWERUP_ENERGY = 3,
	POWERUP_INVULNERABILITY = 4,
	POWERUP_INVISIBILITY = 5,
	POWERUP_AFTERBURNER_COOLER = 6,
	POWERUP_CONVERTER= 7,
	POWERUP_FULLMAP = 8,
	POWERUP_GREEN_BALL = 9,
	POWERUP_GUN_QUADLASERS = 10,
	POWERUP_FLAG_BLUE_ = 11,
	POWERUP_FLAG_RED_ = 12,
	POWERUP_SHIELD = 13,
	POWERUP_MISSILE_CONCUSION = 14,
	POWERUP_CANNON_FUSION = 15,
	POWERUP_MISSILE_GUIDED = 16,
	POWERUP_MISSILE_HOMING = 17,
	POWERUP_MISSILE_MEGA = 18,
	POWERUP_CANNON_OMEGA = 19,
	POWERUP_CANNON_PLASMA = 20,
	POWERUP_MISSILE_SMART = 21,
	POWERUP_GUN_SUPERLASER = 22,
	POWERUP_CYAN_BALL = 23,
	POWERUP_CHAFF4PACK = 24,
	POWERUP_NOVAK_GUY = 25,
	POWERUP_GUN_MASSDRIVER = 26,
	POWERUP_RAPID_FIRE = 27,
	POWERUP_MISSILE_BLACK_SHARK = 28,
	POWERUP_MISSILE_MORTAR =29,
	POWERUP_MISSILE_FRAG = 30,
	POWERUP_MISSILE_NAPALM = 31,
	POWERUP_CANNON_VAUSS = 32,
	POWERUP_GUN_NAPALM = 33,
	POWERUP_MISSILE_CYCLONE = 34,
	POWERUP_AMMO_VAUSS = 35,
	POWERUP_GUN_MICROWAVE = 36,
	POWERUP_CANNON_MICROWAVE = 36,
	POWERUP_CANNON_EMD = 37,
	POWERUP_MISSILE_CONCUSION4PACK = 38,
	POWERUP_MISSILE_FRAG4PACK = 39,
	POWERUP_MISSILE_GUIDED4PACK = 40,
	POWERUP_MISSILE_HOMING4PACK = 41,
	POWERUP_RED_BALL = 42,
	POWERUP_COUNTERMEASURE_SEEKERMINE = 43,
	POWERUP_BETTY4PACK = 44,
	POWERUP_COUNTERMEASURE_GUNBOY = 45,
	POWERUP_FLAG_YELLOW_ = 46,
	POWERUP_FLAG_GREEN_ = 47,
	POWERUP_SECURITY_KEYCARD = 48,
	POWERUP_VIRUS_SAMPLE = 49,
	POWERUP_AMMO_MASSDRIVER = 50,
	POWERUP_NAPALM_FUEL = 51,
	POWERUP_FLAG_RED = 52,
	POWERUP_FLAG_BLUE = 53,
	POWERUP_FLAG_YELLOW = 54,
	POWERUP_FLAG_GREEN = 55,
	POWERUP_ENERGY_FUSE = 56,
	POWERUP_BLACK_BOX = 57,
// (thin)
	POWERUP_ICON_BUILDERS = 58,
// (fat)
	POWERUP_ICON_COLLECTORS = 59,
// (violet, with an eye)
	POWERUP_ICON_CHOSEN = 60,
	POWERUP_GUIDEBOT_WINGNUT = 61,
	POWERUP_GUIDEBOT_GUARDIAN = 62,
	POWERUP_GUIDEBOT_ACCELERATOR = 63,
	POWERUP_GUIDEBOT_EXTINGUISHER = 64,
	POWERUP_GUIDEBOT_MANUAL_CONTROL = 65,
	POWERUP_GUIDEBOT_TEMPORARY_ANTIVIRUS = 66,
	POWERUP_CYAN_SPHERE = 67,
	POWERUP_none_1 = 68,
	POWERUP_FUSE = 69,
	POWERUP_ITEM_1 = 70,
//	POWERUP_SHIP_ITEM_1 = 70,
	POWERUP_SHIP_ITEM_2 = 71,
	POWERUP_SHIP_ITEM_3 = 72,
	POWERUP_KEY_G1 = 73,
	POWERUP_KEY_R1 = 74,
	POWERUP_KEY_Y1 = 75,
	POWERUP_PROXMINES4PACK = 76,
	POWERUP_KEY_xx_1 = 77,
// round key
	POWERUP_KEY_xx_2 = 78,
// haki key
	POWERUP_KEY_xx_3 = 79,
//	POWERUP_ = ,
};

